@extends('layouts.app')
@section('content')
@include('layouts.slider')
@include('partials.mini_slider')
@include('partials.featured')
@include('partials.banner')
@include('partials.latest')
@include('layouts.blog')
@endsection